### ISSUE TITLE
Exception (IOException) thrown if a file of same name exists in output folder

### ISSUE THREAD

**Issue by ethantang95** [Aelphaeis/Dragon-Nest-Resource-Inspector#3]
Found in AmalgamatedPakViewer.cs line 212. Reproduce able by trying to extract files to the same output folder with another file of the same name.

EG: weathertable.dat has been already extracted to some .ext folder. If you try to extract another folder that has weathertable.dat to the same .ext folder, it will cause it to crash.

**Comment by Aelphaeis** [comment]
Going to take a look at this. If its possible can you post a screen shot of the error?

**Comment by ethantang95** [comment]
System.IO.IOException was unhandled
  HResult=-2147024816
  Message=The file 'C:\Users\iMac\Desktop\DNResources\ext\partstable_guild.dnt' already exists.
  Source=mscorlib
  StackTrace:
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
       at System.IO.FileStream..ctor(String path, FileMode mode)
       at DragonNest.ResourceInspector.Pak.Viewer.AmalgamatedPakViewer.Export(TreeNode node, String Location) in c:\Users\iMac\Documents\GitHub\Dragon-Nest-Resource-Inspector\DragonNest.ResourceInspector\Pak.Viewer\AmalgamatedPakViewer.cs:line 212
       at DragonNest.ResourceInspector.Pak.Viewer.AmalgamatedPakViewer.Export(TreeNode node, String Location) in c:\Users\iMac\Documents\GitHub\Dragon-Nest-Resource-Inspector\DragonNest.ResourceInspector\Pak.Viewer\AmalgamatedPakViewer.cs:line 225
       at DragonNest.ResourceInspector.Pak.Viewer.AmalgamatedPakViewer.ExportButton_Click(Object sender, EventArgs e) in c:\Users\iMac\Documents\GitHub\Dragon-Nest-Resource-Inspector\DragonNest.ResourceInspector\Pak.Viewer\AmalgamatedPakViewer.cs:line 205
       at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
       at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
       at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
       at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.ToolStrip.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at DragonNest.ResourceInspector.Program.Main(String[] args) in c:\Users\iMac\Documents\GitHub\Dragon-Nest-Resource-Inspector\DragonNest.ResourceInspector\Program.cs:line 23
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

![image](https://cloud.githubusercontent.com/assets/8282242/5591306/317b5a14-9122-11e4-987e-74b4e69bf4e8.png)

**Comment by Aelphaeis** [comment]
Hi ethantang95: 
Thanks for all your help. I've identified the behavior and changed it in branch 3.1. Please submit or reopen issue if you're still having problems with it.
